redesign

diff --git a/jumpstart/check b/jumpstart/check
--- a/jumpstart/check
+++ b/jumpstart/check
@@ -5,31 +5,58 @@
 # rules.ok file in the same directory as the rules file.
 #
 
-rulesFile="./rules"
-while [[ ! -f $rulesFile ]]
-do
-  echo -e "The rules file: $rulesFile, does not exist."
-  echo -e "Where is the rules file located? [] \c"
-  read rulesFile
-done
+USAGE="
+$0 <rules file>
+"
+
+function cleanExit {
+  if [[ -f $1 ]]
+  then
+    rm $1
+  fi
+  exit $2
+}
 
 sumBin=$(which sum)
 if [[ -z $t || ! -f $t ]]
 then
   echo -e "You need to install a 'sum' tool."
   echo -e "If you have a sum tool installed, then fix your path, and try this again"
+  exit 1
 fi
 
-sed '/^$/d; /^#/d; /^\s/d' $rulesFile > ${rulesFile}.ok
-sum=$($sumBin ${rulesFile}.ok | awk '{print $1}')
-if [[ $sum = 0 ]]
+if [[ -n $1 && -f $1 ]]
 then
-  echo -e "For some reason your rules.ok file is blank.  You will want to"
-  echo -e "look into this issue."
-  echo -e "Ensure that all comments start the line with a '#'."
-  echo -e "There should be no blank lines."
-  echo -e "There should be no lines starting with a space."
-  exit 100
+  rulesFile=$1
+  rulesOkFile="$rulesFile.ok"
+  rulesOkFileBackup="$rulesFile.ok.$$"
+else
+  echo -e "$1 doesn't exist, try again"
+  echo -e "$USAGE"
+  cleanExit "" 1
 fi
 
-echo -e "# version=2 checksum=$sum" >> ${rulesFiles}.ok
+if [[ -f $rulesOkFile ]]
+then
+  operation=$(cp $rulesOkFile $rulesOkFileBackup 2>&1) ||
+  (echo -e "Can't make backup of $rulesOkFile:\n$operation" ; cleanExit 1)
+fi
+
+sed 's/\s\s*/ /g; s/^\s\s*//g; /^#/d; /^$/d' $rulesFile > $rulesOkFileBackup
+
+while read line
+do
+  # Should be 5 words
+  words=$(echo -e "$line" | wc -w)
+  if [[ $words != 5 ]]
+  then
+    echo -e "The following line is invalid:"
+    echo -e "$line"
+    cleanExit $rulesOkFileBackup 1
+  fi
+done < $rulesOkFileBackup
+
+sum=$(sum $rulesOkFile | awk '{print $1}')
+echo -e "# version=2 checksum=$sum" >> $rulesOkFileBackup
+
+mv $rulesOkFileBackup $rulesOkFile
